config/routes.rb
Rails.application.routes.draw do

  
  resources :packages do
    resources :rooms
  end 
  get 'orders/new'

  resources :blocks do 
  	resources :orders
    resources :packages
  end
  
  resources :images
  resources :experiences
  get 'viajes_corporativos' => 'pages#corporativos'
  get 'mis_experiencias' => 'pages#mis_experiencias'

  resources :contacts, only: [:new, :create]
	mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  root 'welcome#index'

  resources :orders, only: [:index]
  resources :packages, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :experience
  has_many :orders, dependent: :destroy
  has_many :packages, dependent: :destroy
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name, 					:validate => false
	attribute :email, 				:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :phone,     		:validate => false
	attribute :service, 			:validate => false
	attribute :donde, 		   	:validate => false
	attribute :comments, 			:validate => false
	attribute :nickname, 			:captcha => true

def headers 
	{
	:subject => "Nueva Confirmación",
	:to => "alex@idearialab.com",
	:cc => "alejandroromo14@gmail.com",
	:from => %("#{name}" <#{email}>)
	}
	end
end

app/models/experience.rb
class Experience < ApplicationRecord
	mount_uploader :foto, FotoUploader
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images

  has_many :blocks, dependent: :destroy
  accepts_nested_attributes_for :blocks, :reject_if => lambda { |a| a[:lugar_salida].blank? }, :allow_destroy => true
  extend FriendlyId
  friendly_id :nombre, use: :slugged

geocoded_by :lugar
after_validation :geocode, if: ->(obj){ obj.lugar.present? and obj.lugar_changed? }
after_validation :lat_changed?

private

# This is used to make sure that our lugar is actually parsed properly and we
# get a valuable lat/long
def lat_changed?
    if (self.lugar_changed?)
        if !(self.latitude_changed?)
            self.errors.add(:lugar, ": La ubicación no es válida")
            return false
        end
    end
    return true
end

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :experience
  mount_uploader :image2, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :block
  



end

app/models/package.rb
class Package < ApplicationRecord
  
  belongs_to :block
  has_many :rooms, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  
  belongs_to :package

validate :habitacion_doble
validate :habitacion_triple
validate :habitacion_cuadruple

def habitacion_doble
	if self.tipo_habitacion == "Habitación Doble" && self.num_adultos >= 3
	errors.add(:room_id, "No se pueden más de dos adultos en habitación doble") 
  end 
end


def habitacion_triple
	if self.tipo_habitacion == "Habitación Triple" && self.num_adultos >= 4
	errors.add(:room_id, "No se pueden más de dos adultos en habitación doble") 
  end 
end


def habitacion_cuadruple
	if self.tipo_habitacion == "Habitación Cuádruple" && self.num_adultos >= 5
	errors.add(:room_id, "No se pueden más de dos adultos en habitación doble") 
  end 
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :experiences

  validates :name, presence: true

  # after_create :create_a_customer

  # def create_a_customer
		# Stripe.api_key = Rails.application.secrets.stripe_secret_key # set the secret key to identify with stripe.	
  	
  # 	customer = Stripe::Customer.create(
  # 		:card => token,
  # 		:email => self.email
  # 		)     
  # 	self.stripe_card_token = customer.id
  # 	save!
  # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :filter_admin!, only: [:mis_experiencias]
  def corporativos
  	@contact = Contact.new

prepare_meta_tags(title: "",
  description: "", 
  keywords: %w[Innovación en México, diferenciación],
      og: {
        site_name: "Inter Travex",
        title: "",
        description: "",
        type: 'website'
      }
)
  end

  def mis_experiencias
    @experiences = Experience.all
  end

  private
    def filter_admin!
     authenticate_user!
     redirect_to root_path, alert: "No tienes acceso" unless current_user.admin?
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@experiences = Experience.where(:disponible => true).limit(3)
  	@q= Experience.where(:disponible => true).ransack(params[:q])
    @experiences = @q.result.uniq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_bread.html.erb
<section>
	<nav>
		<ol class="cd-breadcrumb custom-separator">
			<li class="<%= 'current' if current_page?(mis_experiencias_path) %>"><a href="<%= mis_experiencias_path %>">Experiencias</a></li>
			<li class="<%= 'current' if current_page?(new_experience_path) %>"><a href="<%= new_experience_path %>">Nueva Experiencia</a></li>

			<li class="<%= 'current' if current_page?(orders_path) %>"><a href="<%= orders_path %>">Órdenes de Venta</a></li>
		</ol>
	</nav>
</section>

app/views/welcome/_hero_1.html.erb
<div class="hero">
	<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div id="banner_1">
				<h1 class="titulo white">Las mejores experiencias en México</h1>
				<p class="white hidden-xs">Es momento de tomar un descanso y acompañarnos a disfrutar de las mejores experiencias turísticas, gastronómicas, culturales y tradiciones de México</p>

				<%= link_to new_contact_path do %>
				<button class="button button_blue2">Más información</button>
				<% end %>
			</div>
		</div>
	</div>
	</div>
</div>

app/views/welcome/_hero_2.html.erb
<div class="hero5">
	<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div id="banner_1">
				<h1 class="titulo white">Las mejores experiencias en México</h1>
				<p class="white hidden-xs">Es momento de tomar un descanso y acompañarnos a disfrutar de las mejores experiencias turísticas, gastronómicas, culturales y tradiciones de México</p>

				<%= link_to new_contact_path do %>
				<button class="button button_blue2">Más información</button>
				<% end %>
			</div>
		</div>
	</div>
	</div>
</div>

app/views/welcome/_hero_3.html.erb
<div class="hero6">
	<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div id="banner_1">
				<h1 class="titulo white">Las mejores experiencias en México</h1>
				<p class="white hidden-xs">Es momento de tomar un descanso y acompañarnos a disfrutar de las mejores experiencias turísticas, gastronómicas, culturales y tradiciones de México</p>

				<%= link_to new_contact_path do %>
				<button class="button button_blue2">Más información</button>
				<% end %>
			</div>
		</div>
	</div>
	</div>
</div>

app/views/welcome/_hero_4.html.erb
<div class="hero7">
	<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div id="banner_1">
				<h1 class="titulo white">Las mejores experiencias en México</h1>
				<p class="white hidden-xs">Es momento de tomar un descanso y acompañarnos a disfrutar de las mejores experiencias turísticas, gastronómicas, culturales y tradiciones de México</p>

				<%= link_to new_contact_path do %>
				<button class="button button_blue2">Más información</button>
				<% end %>
			</div>
		</div>
	</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="owl-carousel">
<%= render 'hero_1' %>
<%= render 'hero_2' %>
<%= render 'hero_3' %>
<%= render 'hero_4' %>
</div> 

<div class="container">
	<div id="titulos">
		<h1 class="titulo center">Conoce a México como nadie lo ha hecho</h1>
		<p class="center">Desde el más pequeño pueblo, la experiencia más desconocida <br>y los mejores paisajes de México, Inter Travex será tu mejor guía</p>
	</div>
</div>

<div class="container">
	<div id="nume">
	<div class="row">
		<div class="col-md-2 col-xs-4 col-md-offset-3">
			<div id="nume_1">
				<%= image_tag "icono_01.png" %>
				<h3>+ 30,000</h3>
				<p>Usuarios Satisfechos</p>
			</div>
		</div>

		<div class="col-md-2 col-xs-4">
			<div id="nume_1">
				<%= image_tag "icono_02.png" %>
				<h3>+ 120</h3>
				<p>Diferentes Experiencias</p>
			</div>
		</div>

		<div class="col-md-2 col-xs-4">
			<div id="nume_1">
				<%= image_tag "icono_03.png" %>
				<h3>+ 1,000</h3>
				<p>Servicios Exitosos</p>
			</div>
		</div>
	</div>
</div>
</div>

<div class="container">
<div id="search">
	<%= search_form_for @q do |f| %>
	<ul>
		<li>
			<%= f.search_field :nombre_cont, placeholder: "Buscar por Lugar...", id: "icon", sytle: "text-indent:30px;"  %>
		</li>
		<li>
			<%= f.search_field :categoria_cont, placeholder: "Tipo de Experiencia...", id: "icon2", sytle: "text-indent:30px;"  %>
		</li>
		<li>
			<%= f.search_field :categoria_cont, id: "icon3", sytle: "text-indent:30px;", placeholder: " Número de días..."  %>
		</li>
		<li>
			
			<%= f.submit "Buscar", class: "button2 button_blue" %>
		</li>
	</ul>
	<% end %>
</div>
</div>


<div class="container">
<div id="expes">
	<div class="row">

<% @experiences.each do |experience| %>
<div class="col-md-4 col-sm-6">
      <div id="expes_1">
      <div class="imagen">
        <%= image_tag experience.foto %>
      </div>
      <div class="datos">
        <h5><%= experience.categoria %></h5>
        <h3><%= experience.nombre %></h3>
        <h6> <span class="fa fa-map-marker"> </span> <%= experience.lugar %></h6>
        <%= link_to experience do %>
        <button class="button button_blue2">Conoce más! -></button>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>


</div>

<br>
<%= link_to experiences_path do %>
<button class="button button_blue button_center">Todas las experiencias</button>
<% end %>
<br>
</div>
</div>

<hr>

<div class="container">
<div id="secciones">
	<div class="row">
		<div class="col-md-6">
			<div id="izq_2" class="left">
				<%= image_tag "banner_home1.jpg" %>
				<h1 class="titulo">Experiencias para Corporativos</h1>
				<p>Nuestra experiencia y calidad en el servicio nos catalogan como los mejores en experiencias a través de México. Si tu empresa requiere de un servicio personalizado, nosotros te llevamos, te organizamos y te operamos todo.</p>
				<%= link_to viajes_corporativos_path do %>
				<button class="button button_blue">Más información</button>
				<% end %>
			</div>
		</div>

		<div class="col-md-6">
			<div id="izq_3" class="right">
				<%= image_tag "banner_home2.jpg" %>
				<h1 class="titulo">Experiencias para Grupos</h1>
				<p>Ya sea una convención, un evento familiar o simplemente un paseo, nosotros te organizamos el viaje con la garantía de que cada persona del grupo disfutará a lo grande la experiencia y sin duda querrán regresar pronto. </p>

				<%= link_to new_contact_path do %>
				<button class="button button_blue">Más información</button>
				<% end %>
			</div>
		</div>
	</div>
</div>
</div>


<div id="contacto">
	<br>
	<h1 class="center white">Somos tu mejor opción para experiencias</h1>
	<p class="center white">12 años en la industria de transporte nos hacen líderes en la organización, planeación y operación de experiencias en México.</p> <br><br>
<%= link_to new_contact_path do %>
<button class="button button_blue button_center">Contáctanos</button>
<% end %>
</div>


<script>
var owl = $('.owl-carousel');
owl.owlCarousel({
    items:1,
    loop:true,
    margin:10,
    autoPlay:true,
    autoplayTimeout:1000,
    autoplayHoverPause:true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:2,
            nav:true
        },
        1000:{
            items:1,
            nav:true,
            loop:true
        }
    }
});
</script>