config/routes.rb
Rails.application.routes.draw do

  
  resources :packages do
    resources :rooms
  end 
  get 'orders/new'

  resources :blocks do 
  	resources :orders
    resources :packages
  end
  
  resources :images
  resources :experiences
  get 'viajes_corporativos' => 'pages#corporativos'
  get 'mis_experiencias' => 'pages#mis_experiencias'

  resources :contacts, only: [:new, :create]
	mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  root 'welcome#index'

  resources :orders, only: [:index]
  resources :packages, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :block
  



end

app/controllers/orders_controller.rb
# app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	
	def new
		@block = Block.find(params[:block_id])
		@order = @block.orders.new
	end

	def show
		@order = Order.find(params[:id])
    @block = Block.find(params[:block_id])
		@price = @order.block.precio_adulto.to_f / 100
	end

  def index
    @orders = Order.all
  end


def create

  @block = Block.find(params[:block_id])
  @order = @block.orders.new(order_params)

  if @order.save

    Stripe.api_key = Rails.application.secrets.stripe_secret_key # set the secret key to identify with stripe.

    
    Stripe::Charge.create(
      :description => @block.experience.nombre,
      :amount => ((@block.precio_adulto.round*100)*@order.many)+((@block.precio_nino.round*100)*@order.many_n)+ @order.total.round*100,
      :currency => "mxn",
      :card => @order.stripe_token # obtained with Stripe.js
    )
    flash[:success] = "Gracias por comprar #{@block.experience.nombre}"
    redirect_to block_order_path(@block, @order)
  else

    flash[:error] = "Oops, algo salió mal"
    render :new
  end
rescue Stripe::CardError => e
  body = e.json_body
  err  = body[:error]
  flash[:error] = err[:message]
  render :new
end


	private
	def order_params
		params.require(:order).permit(:stripe_token, :block_id, :many, :many_n, :hab_doble, :hab_triple, :hab_cuadrupple, :menor_ex, :total, :mas_adultos, :mas_menores, :nombre, :email)
	end
end


# The syntax above will only find and permit the "stripe_token" attribute if it's nested inside "order".

# params = {
#   "utf8" => "✓",
#   "authenticity_token" => "sSlwx4lcH8pQYHrT9C5RR50sgbsazaCw16SegVsoiaA=",
#   "order" => {
#     "stripe_token"=>"tok_14pfah2uVktQRyY5UIs2cIhP"
#   },
#   "action" => "create",
#   "controller" => "orders",
#   "block_id" => "1"
# }

# To achieve that we appended "<input name="order[stripe_token]" />" to our form using jQuery.

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_dere.html.erb
<div id="contact2">
	<h2 class="titulo">Información General</h2>
	<hr>

	<div id="im">
	<%= image_tag @block.experience.foto %>
	</div>
	<br>
	<h5 class="center"><%=@block.experience.nombre %></h5>

	<p><%=simple_format @block.experience.descripcion %></p>


<%  if @block.experience.dias == "1 día" %>

<div id="table">
<div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
					<th>#</th>
					<th></th>
					<th></th>
        </thead>
        <tbody>
          <tr>
          	<td><span id="max_many"></span></td>
					<td><%=number_to_currency(@block.precio_adulto)%> x/adulto</td>
					<td>$ <span id="multiple">0</span> </td>
          </tr>

          <tr>
					<td></td>
					<td></td>
					<td></td>
          </tr>

          <tr>
          	<td><span id="max_many2"></span></td>
					<td><%=number_to_currency(@block.precio_nino) %> x/ niño</td>
					<td>$ <span id="multiple2">0</span></td>
          </tr>

          <tr>
					<td></td>
					<td></td>
					<td></td>
          </tr>

          <tr>
					<td></td>
					<td>Total:</td>
					<td>$ <span id="fene">0</span></td>
          </tr>
        </tbody>
      </table>
    </div>
</div>

<% else %>


<div id="table">
<div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
					<th>#</th>
					<th></th>
					<th></th>
        </thead>
        <tbody>
          <tr>
          	<td><span id="max_many3"></span></td>
					<td><%=number_to_currency(@block.habitacion_doble)%> x/ 2 personas en habitación doble</td>
					<td>$ <span id="multiple3">0</span> </td>
          </tr>

          <tr>
					<td></td>
					<td></td>
					<td></td>
          </tr>

          <tr>
          	<td><span id="max_many4"></span></td>
					<td><%=number_to_currency(@block.habitacion_triple) %> x/ 3 personas en  habitación triple</td>
					<td>$ <span id="multiple4">0</span></td>
          </tr>

          <tr>
					<td></td>
					<td></td>
					<td></td>
          </tr>

          <tr>
          	<td><span id="max_many5"></span></td>
					<td><%=number_to_currency(@block.habitacion_cuadruple) %> x/ 4 personas en  habitación cuádruple</td>
					<td>$ <span id="multiple5">0</span></td>
          </tr>


          <tr>
					<td></td>
					<td></td>
					<td></td>
          </tr>

          <tr>
          	<td><span id="max_many6"></span></td>
					<td><%=number_to_currency(@block.menor_extra) %> x/  menor extra</td>
					<td>$ <span id="multiple6">0</span></td>
          </tr>

          <tr>
					<td></td>
					<td></td>
					<td></td>
          </tr>

          <tr>
					<td></td>
					<td>Total:</td>
					<td>$ <span id="fene">0</span></td>
          </tr>
        </tbody>
      </table>
    </div>
</div>


<% end %>

</div>

app/views/orders/_izqui.html.erb
<%= form_for [@block, @order], id: "new_order" do |f| %>
<span class="payment-errors"></span>



<%  if @block.experience.dias == "1 día" %>
<div id="contact2">

	<h2 class="titulo">Pasajeros</h2>
	<hr>

	<div class="row">
		<div class="col-md-6">
			<%= f.label :Cuántos_adultos %>
			<%= f.select :many, [["0", 0],["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6", 6], ["7", 7], ["8", 8]], required: true%>
		</div>

		<div class="col-md-6">
			<%= f.label :Cuántos_niños %>
			<%= f.select :many_n, [["0", 0],["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6", 6], ["7", 7], ["8", 8]], required: true%>
		</div>
	</div>


</div>



<% else %>

<div id="contact2">
		<h2 class="titulo">Pasajeros</h2>
	<hr>

	<div class="row">
		<div class="col-md-6">
			<%= f.label :Cuántos_adultos %>
			<%= f.select :mas_adultos, [["0", 0],["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6", 6], ["7", 7], ["8", 8]], required: true%>
		</div>

		<div class="col-md-6">
			<%= f.label :Cuántos_niños %>
			<%= f.select :mas_menores, [["0", 0],["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6", 6], ["7", 7], ["8", 8]], required: true%>
		</div>
	</div>


</div>

<div id="contact2">

	<h2 class="titulo">Habitaciones</h2>
	<hr>

	<div class="row">
		<div class="col-md-6">
			<%= f.label :Habitación_doble %>
			<%= f.select :hab_doble, [["0", 0],["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5]], required: true%>
		</div>

		<div class="col-md-6">
			<%= f.label :Habitación_triple %>
			<%= f.select :hab_triple, [["0", 0],["1", 1], ["2", 2], ["3", 3], ["4", 4]], required: true%>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<%= f.label :Habitación_cuádruple %>
			<%= f.select :hab_cuadrupple, [["0", 0],["1", 1], ["2", 2], ["3", 3]], required: true%>
		</div>

		<div class="col-md-6">
			<%= f.label :Menor_extra %>
			<%= f.select :menor_ex, [["0", 0],["1", 1]], required: true%>
		</div>
	</div>



  <div class="field hidden">
    <%= f.label :total %>
    <%= f.number_field :total, id: "totalimus" %>
  </div>

</div>

<% end %>


<div id="contact2">

	<br>
	<div class='card-wrapper'></div>
	<br>

<div class="row">
    <div class="col-md-6">
      <div class="field">
        <%= f.label :nombre %>
        <%= f.text_field :nombre, required:true %>
      </div>
  </div>

  <div class="col-md-6">
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email, required:true %>
      </div>
  </div>  
</div>

	<div class="row">
		<div class="col-md-6">
			<%= f.label :número_de_tarjeta %>
			<input type="text" name="number" data-stripe= "number" size="16" id= "tar" >
		</div>

		<div class="col-md-6">
			<%= f.label :nombre_de_la_tarjeta %>
			<input type="text" name="first-name" data-stripe= "name"/>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-9">
			<%= f.label :_fecha_de_expiración %>
			<input type="text" name="expiry"/ id="expiry2">
		</div>

		<div class="col-xs-3">
			<%= f.label :cvc %>
			<input type="text" name="cvc" data-stripe= "cvc" size="4"/>
		</div>
	</div>

	<input type="text" size="2" data-stripe="exp-month" id="exo_month" class="hidden" />
	<input type="text" size="4" data-stripe="exp-year" id="exo_year" class="hidden" />

	<button type="submit" class="button button_blue button_block">Pagar Ahora $ <span id="total">0</span></button>

</div>

<% end %>



<script>
$(function() {
var text = $('#multiple');
var texto = $('#multiple2');
var texto = $('#multiple3');
var texto = $('#multiple4');
var texto = $('#multiple5');
var texto = $('#multiple6');
var totis = $('#fene');



$('#order_many').change(function() { 
	var soup = $(this).val();
	var noup = <%= @block.precio_adulto %>;
	var totalip1 = soup * noup;
	document.getElementById('max_many').innerHTML = soup;
	document.getElementById('multiple').innerHTML = totalip1;
	var mex = parseInt(document.getElementById('multiple').innerHTML) + parseInt(document.getElementById('multiple2').innerHTML);
	document.getElementById('fene').innerHTML = mex;

	document.getElementById('total').innerHTML = totis.text();
	document.getElementById('totalimus').value = totis.text();


});


$('#order_many_n').change(function() { 
	var soup = $(this).val();
	var noup = <%= @block.precio_nino %>;
	var totalip2 = soup * noup;
	document.getElementById('max_many2').innerHTML = soup;
	document.getElementById('multiple2').innerHTML = totalip2;
	var mex2 = parseInt(document.getElementById('multiple').innerHTML) + parseInt(document.getElementById('multiple2').innerHTML);
	document.getElementById('fene').innerHTML = mex2;

	document.getElementById('total').innerHTML = totis.text();
	document.getElementById('totalimus').value = totis.text();
});





$('#order_hab_doble').change(function() { 
	var soup = $(this).val();
	var noup = <%= @block.habitacion_doble %>;
	var totalip3 = soup * noup *2;
	document.getElementById('max_many3').innerHTML = soup;
	document.getElementById('multiple3').innerHTML = totalip3;
	var mex3 = parseInt(document.getElementById('multiple4').innerHTML) + parseInt(document.getElementById('multiple3').innerHTML) + parseInt(document.getElementById('multiple5').innerHTML) + parseInt(document.getElementById('multiple6').innerHTML);
	document.getElementById('fene').innerHTML = mex3;

	document.getElementById('total').innerHTML = totis.text();
	document.getElementById('totalimus').value = totis.text();
});


$('#order_hab_triple').change(function() { 
	var soup = $(this).val();
	var noup = <%= @block.habitacion_triple %>;
	var totalip4 = soup * noup* 3;
	document.getElementById('max_many4').innerHTML = soup;
	document.getElementById('multiple4').innerHTML = totalip4;
	var mex4 = parseInt(document.getElementById('multiple4').innerHTML) + parseInt(document.getElementById('multiple3').innerHTML) + parseInt(document.getElementById('multiple5').innerHTML) + parseInt(document.getElementById('multiple6').innerHTML);
	document.getElementById('fene').innerHTML = mex4;

	document.getElementById('total').innerHTML = totis.text();
	document.getElementById('totalimus').value = totis.text();
});


$('#order_hab_cuadrupple').change(function() { 
	var soup = $(this).val();
	var noup = <%= @block.habitacion_cuadruple %>;
	var totalip5 = soup * noup * 4;
	document.getElementById('max_many5').innerHTML = soup;
	document.getElementById('multiple5').innerHTML = totalip5;
	var mex5 = parseInt(document.getElementById('multiple4').innerHTML) + parseInt(document.getElementById('multiple3').innerHTML) + parseInt(document.getElementById('multiple5').innerHTML) + parseInt(document.getElementById('multiple6').innerHTML);
	document.getElementById('fene').innerHTML = mex5;

	document.getElementById('total').innerHTML = totis.text();
	document.getElementById('totalimus').value = totis.text();
});


$('#order_menor_ex').change(function() { 
	var soup = $(this).val();
	var noup = <%= @block.menor_extra %>;
	var totalip6 = soup * noup;
	document.getElementById('max_many6').innerHTML = soup;
	document.getElementById('multiple6').innerHTML = totalip6;
	var mex6 = parseInt(document.getElementById('multiple4').innerHTML) + parseInt(document.getElementById('multiple3').innerHTML) + parseInt(document.getElementById('multiple5').innerHTML) + parseInt(document.getElementById('multiple6').innerHTML);
	document.getElementById('fene').innerHTML = mex6;

	document.getElementById('total').innerHTML = totis.text();
	document.getElementById('totalimus').value = totis.text();
});





});

</script>

app/views/orders/index.html.erb
<%= render 'welcome/bread' %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-headline">
      <div class="panel-heading">
        <h3>Órdenes Recibidas</h3>
        <hr>
      </div>
      <div class="panel-body">
 <div class="content table-responsive table-full-width">
			<table class="table table-hover table-striped">
				<thead>
					<th>ID</th>
					<th>Bloque</th>
					<th>Experiencia</th>
					<th>Email</th>
					<th>Número de adultos</th>
					<th>Número de niños</th>
					<th>Habitación doble</th>
					<th>Habitación triple</th>
					<th>Habitación cuadruple</th>
					<th>Menos Extra</th>
					<th>Total pagado</th>
					<th colspan="3"></th>
				</thead>
				<tbody>
					<% @orders.each do |order| %>
					<% if order.stripe_token.present? %>
					<tr>
						<td><%= order.id%></td>
						<td><%= order.block.id%></td>
						<td><%= order.block.experience.nombre %></td>
						<td><%= order.email %></td> 
						<td><%= order.many%></td>
						<td><%= order.many_n%></td>
						<td><%= order.hab_doble%></td>
						<td><%= order.hab_triple%></td>
						<td><%= order.hab_cuadrupple%></td>
						<td><%= order.menor_ex%></td>
						<td><%= number_to_currency ((order.block.precio_adulto)* order.many)+((order.block.precio_nino)* order.many_n)+ order.total%></td>
            <td><%= link_to 'Ver más', block_order_path(order.block, order) %></td>
            <td><%= link_to 'Editar', edit_block_order_path(order.block, order) %></td>
            <td><%= link_to 'Eliminar', block_order_path(order.block, order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
					<% end %>
					<% end %>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
					<tr>            
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>       
      </div>
    </div>
  </div>
</div>	

app/views/orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 col-md-offset-1">
      <%= render 'dere'%>
    </div>
    <div class="col-md-5">
      <%= render 'izqui' %>
    </div>
  </div>
</div>



<script>
  var card = new Card({
    form: 'form',
    container: '.card-wrapper',

    formSelectors: {
      nameInput: 'input[name="first-name"]'
    },

    placeholders: {
      number: '**** **** **** ****',
      name: 'Bruno Diaz',
      expiry: '**/****',
      cvc: '***'
    }
  });

  

  $("#expiry2").keyup(function(){
    var firstChar = $('#expiry2').val().substr(0, 2);
    document.getElementById('exo_month').value = parseInt(firstChar);
  });

  $("#expiry2").keyup(function(){
    var firstChar = $('#expiry2').val().substr(4, 6);
    document.getElementById('exo_year').value = parseInt(firstChar);
  });


</script>

app/views/orders/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div id="contact2">

				<% if @order.stripe_token.present?%>
				<h2><%=@order.nombre%></h2>
				<p class="center"><%=@order.email%></p>
				<h2>Gracias por Reservar <br>	"<%= @order.block.experience.nombre %>" </h2>
				<div id="im">
					<%= image_tag @block.experience.foto %>
				</div>
				<p class="center">Para Inter Travex será un honor tenerte a ti y tu familia con nosotros viviendo esta gran aventura. Estos son los detalles de tu compra:</p>
				<div id="informacion"> 

					<div class="row">
						<div class="col-md-6">
							<h3>Fecha de salida:</h3>
							<h6><%= @block.fecha_salida %></h6>
						</div>

						<div class="col-md-6">
							<h3>Fecha de regreso:</h3>
							<h6><%= @block.fecha_regreso %></h6>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6">
							<h3>Lugar de salida:</h3>
							<h6><%= @block.lugar_salida %></h6>
						</div>

						<div class="col-md-6">
							<h3>Hora de salida:</h3>
							<h6><%= @block.hora_salida.strftime("%H:%M") %>hrs.</h6>
						</div>
					</div>

				</div>
				<br><br>

				<%  if @block.experience.dias == "1 día" %>
				<div id="table">
					<div class="content table-responsive table-full-width">
						<table class="table table-hover table-striped">
							<thead>
								<th></th>
								<th></th>
								<th></th>
							</thead>
							<tbody>
								<tr>
									<td><%= @order.many %></td>
									<td><%=number_to_currency(@block.precio_adulto)%> x/ adulto</td>
									<td><%= @a= number_to_currency(@block.precio_adulto * @order.many) %></td>
								</tr>

								<tr>
									<td></td>
									<td></td>
									<td></td>
								</tr>

								<tr>
									<td><%= @order.many_n%></td>
									<td><%=number_to_currency(@block.precio_nino) %> x/ niño</td>
									<td><%= @b= number_to_currency(@block.precio_nino * @order.many_n) %></td>
								</tr>

								<tr>
									<td></td>
									<td></td>
									<td></td>
								</tr>

								<tr>
									<td></td>
									<td></td>
									<td>Total: <%= number_to_currency((@block.precio_nino * @order.many_n) + (@block.precio_adulto * @order.many))%></td>

								</tr>
							</tbody>
						</table>
					</div>
				</div>

				<% else %>

				<div id="table">
<div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
					<th></th>
					<th></th>
					<th></th>
        </thead>
        <tbody>
          <tr>
          	<td><span id="max_many3"></span></td>
					<td><%=number_to_currency(@doble1 = @block.habitacion_doble)%> x <%= @doble2 = @order.hab_doble%> persona(s) en habitación doble</td>

					<td><%= number_to_currency @dobletotal = @doble1 * @doble2 %></td>
          </tr>

          <tr>
					<td></td>
					<td></td>
					<td></td>
          </tr>

          <tr>
          	<td><span id="max_many4"></span></td>
					<td><%=number_to_currency(@triple1 = @block.habitacion_triple) %> x <%= @triple2 = @order.hab_triple %> persona(s) en  habitación triple</td>

					<td><%=number_to_currency  @tripletotal = @triple1 * @triple2 %></td>
          </tr>

          <tr>
					<td></td>
					<td></td>
					<td></td>
          </tr>

          <tr>
          	<td><span id="max_many5"></span></td>
					<td><%=number_to_currency(@cuad1 = @block.habitacion_cuadruple) %> x <%= @cuad2 = @order.hab_cuadrupple %> persona(s) en  habitación cuádruple</td>

					<td><%= number_to_currency @cuadtotal = @cuad1 * @cuad2 %></td>
          </tr>


          <tr>
					<td></td>
					<td></td>
					<td></td>
          </tr>

          <tr>
          	<td><span id="max_many6"></span></td>
					<td><%=number_to_currency(@men1= @block.menor_extra) %> x <%= @men2 = @order.menor_ex %> menor(es) extra</td>

					<td><%= number_to_currency @mentotal = @men1 * @men2 %></td>
          </tr>

          <tr>
					<td></td>
					<td></td>
					<td></td>
          </tr>

          <tr>
					<td></td>
					<td>Total:</td>
					<td><%=  number_to_currency @grantotal =  @dobletotal + @tripletotal + @cuadtotal + @mentotal %></td>
          </tr>
        </tbody>
      </table>
    </div>
</div>	


				<% end %>
				<p class="center">Descarga más información:</p> <br>
				<%= link_to block_order_path(@block, @order, format: 'pdf') do %>
				<button class="button button_blue button_center">Descargar Información</button>
				<% end %>
				<p class="center">Stripe token: <%= @order.stripe_token %></p>
	
		<% else %>
				<h2>Lo sentimos, tu pedido no pudo ser completado</h2>
				<p class="center">Vuelve a intentarlo, ningún cobro se ha realizado.</p>
				<p class="center">Muchas gracias</p> <br><br>
				<%= link_to "Regresar al inicio", root_path, class: "button button_blue button_center" %>
			<% end %>
			</div>
		</div>
	</div>
</div>