config/routes.rb
Rails.application.routes.draw do

  
  resources :packages do
    resources :rooms
  end 
  get 'orders/new'

  resources :blocks do 
  	resources :orders
    resources :packages
  end
  
  resources :images
  resources :experiences
  get 'viajes_corporativos' => 'pages#corporativos'
  get 'mis_experiencias' => 'pages#mis_experiencias'

  resources :contacts, only: [:new, :create]
	mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  root 'welcome#index'

  resources :orders, only: [:index]
  resources :packages, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/experience.rb
class Experience < ApplicationRecord
	mount_uploader :foto, FotoUploader
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images

  has_many :blocks, dependent: :destroy
  accepts_nested_attributes_for :blocks, :reject_if => lambda { |a| a[:lugar_salida].blank? }, :allow_destroy => true
  extend FriendlyId
  friendly_id :nombre, use: :slugged

geocoded_by :lugar
after_validation :geocode, if: ->(obj){ obj.lugar.present? and obj.lugar_changed? }
after_validation :lat_changed?

private

# This is used to make sure that our lugar is actually parsed properly and we
# get a valuable lat/long
def lat_changed?
    if (self.lugar_changed?)
        if !(self.latitude_changed?)
            self.errors.add(:lugar, ": La ubicación no es válida")
            return false
        end
    end
    return true
end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]
  before_action :filter_admin!, except: [:show, :index]

  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = Experience.all

    @q= Experience.where(:disponible => true).ransack(params[:q])
    @experiences = @q.result.uniq

    prepare_meta_tags(title: "",
      description: "", 
      keywords: %w[Innovación en México, diferenciación],
      og: {
        site_name: "Inter Travex",
        title: "",
        description: "",
        type: 'website'
      }
      )

  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
    @experiences = Experience.where(:disponible => true).order('id ASC').limit(3)
    @contact = Contact.new
    @images = @experience.images.all
    @blocks = @experience.blocks.where("fecha_salida >= ?", Time.zone.now.beginning_of_day).order('id ASC')

    prepare_meta_tags(title: "",
      description: "", 
      keywords: %w[Innovación en México, diferenciación],
      og: {
        site_name: "Inter Travex",
        title: "",
        description: "",
        type: 'website'
      }
      )
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
    @image = @experience.images.build
  end

  # GET /experiences/1/edit
  def edit
    @images = @experience.images
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)
    @experience.user_id = current_user.id

    if @experience.save

      if params[:images_p] 
        params[:images_p].each do |image|
          @experience.images.create(image2: image)
        end
      end

      @images = @experience.images
      redirect_to edit_experience_path(@experience), notice: "Saved..."
    else
      render :new
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    if @experience.update(experience_params)

      if params[:images_p] 
        params[:images_p].each do |image|
          @experience.images.create(image2: image)
        end
      end

      redirect_to edit_experience_path(@experience), notice: "Updated..."
    else
      render :edit
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.friendly.find(params[:id])
    end

    def filter_admin!
     authenticate_user!
     redirect_to root_path, alert: "No tienes acceso" unless current_user.admin?
   end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:disponible, :nombre, :lugar, :categoria, :dias, :foto, :slug, :user_id, :incluye, :itinerario, :que_plan, :recomendaciones, :address, :latitude, :longitude, :descripcion, :politics, images_attributes: [:id, :experience_id, :image2], blocks_attributes: [:id, :experience_id, :fecha_salida, :lugar_salida, :hora_salida, :fecha_regreso, :precio_adulto, :precio_nino, :capacidad, :habitacion_doble, :habitacion_triple, :habitacion_cuadruple, :menor_extra, :_destroy])
    end
  end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_block_fields.html.erb
<div class="nested-fields">
<div class="row">
  <div class="col-md-3">
  <div class="field">
    <%= f.label :fecha_salida %><br>
    <%= f.date_field :fecha_salida, required:true %>
  </div>
  </div>

  <div class="col-md-3">
  <div class="field">
    <%= f.label :lugar_salida %><br>
    <%= f.text_field :lugar_salida %>
  </div>
  </div>

 <div class="col-md-3">
  <div class="field">
    <%= f.label :hora_salida %><br>
    <%= f.time_field :hora_salida %>
  </div>
  </div>

 <div class="col-md-3">
  <div class="field">
    <%= f.label :fecha_regreso %><br>
    <%= f.date_field :fecha_regreso, required:true %>
  </div>
  </div>

</div>

<div class="row">


 <div class="col-md-3">
  <div class="field">
    <%= f.label :precio_de_adulto %><br>
    <%= f.number_field :precio_adulto, step: :any, required:true %>
  </div>
  </div>

 <div class="col-md-3">
  <div class="field">
    <%= f.label :precio_de_niño %><br>
    <%= f.number_field :precio_nino, step: :any, required:true %>
  </div>
  </div>

 <div class="col-md-3">
  <div class="field">
    <%= f.label :capacidad %><br>
    <%= f.number_field :capacidad, required:true %>
  </div>
  </div>
  
</div>


<div class="row">


 <div class="col-md-3">
  <div class="field">
    <%= f.label :precio_por_habitacion_doble %><br>
    <%= f.number_field :habitacion_doble, step: :any, required:true %>
  </div>
  </div>

 <div class="col-md-3">
  <div class="field">
    <%= f.label :precio_por_habitacion_triple %><br>
    <%= f.number_field :habitacion_triple, step: :any, required:true %>
  </div>
  </div>

 <div class="col-md-3">
  <div class="field">
    <%= f.label :precio_por_habitacion_cuadruple %><br>
    <%= f.number_field :habitacion_cuadruple, step: :any, required:true %>
  </div>
  </div>

 <div class="col-md-3">
  <div class="field">
    <%= f.label :precio_menor_extra %><br>
    <%= f.number_field :menor_extra, step: :any, required:true %>
  </div>
  </div>
  
</div>

<%= link_to_remove_association "Quitar Paquete", f %>
<hr>
<hr>
</div>

app/views/experiences/_form.html.erb
<%= form_with(model: experience, local: true) do |form| %>
  <% if experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div id="contact2">
  <h2>Habilitar Experiencia</h2>
  <div class="field">
    <%= form.label :disponible %>
    <%= form.check_box :disponible, id: :experience_disponible %>
  </div>
</div>


<div id="contact2">
  <h2>Información General</h2>
  <div class="field">
    <%= form.label :nombre_de_la_experiencia %>
    <%= form.text_field :nombre, id: :experience_nombrex, required: true %>
  </div>

  <div class="field">
    <%= form.label :lugar_de_la_experiencia %>
    <%= form.text_field :lugar, id: :experience_lugar, required: true %>
  </div>

  <div class="field">
    <%= form.label :categoria %>
    <%= form.text_field :categoria, id: :experience_categoria, required: true %>
  </div>

  <div class="field">
    <%= form.label :dias %>
    <%= form.select :dias, [["1 día"], ["Fin de semana"], ["Puente"], ["Semana completa"]], {:prompt => 'Elige Número de días'}, {:required => true}%>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :experience_descripcion, required: true %>
  </div>
</div>

<div id="contact2">

  <div class="field">
    <%= form.label :foto_principal %><br>
    <%= @experience.foto if @experience.foto %>
    <br><br>
    <%= form.file_field :foto %>
    <%= form.hidden_field :foto_cache %>
  </div>
</div>

<div id="contact2">
  <h2>Imágenes de Carrusel</h2>
  <div class="row">
  <div class="col-md-4">
    <div class="form-group">              
      <span class="btn btn-default">
        <i class="fa fa-cloud-upload fa-lg"></i> Subir fotos 
        <%= file_field_tag "images_p[]", type: :file, multiple: true %>
      </span>
    </div>    
  </div>
</div>

<div id="photos_p"><%= render 'images/list' %></div>
</div>

<div id="contact2">
  <div class="field">
    <%= form.label :qué_incluye? %>
    <%= form.text_area :incluye, id: :experience_incluye %>
  </div>

  <div class="field">
    <%= form.label :cuál_es_el_itinerario? %>
    <%= form.text_area :itinerario, id: :experience_itinerario %>
  </div>

  <div class="field">
    <%= form.label :Cuál_es_el_plan? %>
    <%= form.text_area :que_plan, id: :experience_que_plan %>
  </div>

  <div class="field">
    <%= form.label :recomendaciones %>
    <%= form.text_area :recomendaciones, id: :experience_recomendaciones %>
  </div>

  <div class="field">
    <%= form.label :políticas %>
    <%= form.text_area :politics %>
  </div>
</div>

<hr>

<div id="contact2">
  <h2>Paquetes</h2>
  <%= form.fields_for :blocks do |block| %>

  <%= render "block_fields", f: block %>
  <% end %>
      <br>
      <div class="links">
        <%= link_to_add_association 'Añadir Paquete', form, :blocks, class: "button button_blue" %>
      </div>
      <br>
</div>

  <div class="actions">
    <%= form.submit class: "button button_blue button_center" %>
  </div>
<% end %>

app/views/experiences/_share.html.erb
<hr>
<div id="share">
  <p>Comparte esta experiencia: </p>

  <ul>

    <li>
    <a class="icon-facebook" rel="nofollow"
    href="http://www.facebook.com/"
    onclick="popUp=window.open(
      'http://www.facebook.com/sharer.php?u=<%="#{request.original_url}"%>',
      'popupwindow',
      'scrollbars=yes,width=800,height=400');
    popUp.focus();
    return false">
    <i class="fa fa-facebook fa-lg face"></i>
  </a>
</li>


  <li>
  <a class="icon-twitter" rel="nofollow"
  href="http://twitter.com/"
  onclick="popUp=window.open(
    'http://twitter.com/intent/tweet?text=\'<%= @experience.nombre %>\' via Inter Travex - <%="#{request.original_url}"%>',
    'popupwindow',
    'scrollbars=yes,width=800,height=400');
  popUp.focus();
  return false">
  <i class="fa fa-twitter fa-lg twitter"></i>
</a>
</li>


<li>
<a class="icon-pinterest" rel="nofollow"
href="http://www.pinterest.com/"
onclick="popUp=window.open(
  'http://pinterest.com/pin/create/button/?url=<%="#{request.original_url}"%>&amp;media=<%= @experience.foto %>&amp;description=<%= @experience.nombre %>',
  'popupwindow',
  'scrollbars=yes,width=800,height=400');
popUp.focus();
return false">
<i class="fa fa-pinterest fa-lg you"></i>
</a>
</li>


<li>
<a class="icon-gplus" rel="nofollow"
href="http://www.plus.google.com/"
onclick="popUp=window.open(
  'https://plus.google.com/share?url=<%="#{request.original_url}"%>',
  'popupwindow',
  'scrollbars=yes,width=800,height=400');
popUp.focus();
return false">
<i class="fa fa-google-plus fa-lg you"></i>
</a> 
</li>   

  </ul>
</div>

<hr>

app/views/experiences/_tabs.html.erb
<div id="tabs">
      <div class="tab">
  <button class="tablinks" onclick="openCity(event, 'London')" id="defaultOpen"> <span class="fa fa-info-circle"></span> Información</button>
  <button class="tablinks" onclick="openCity(event, 'Paris')"> <span class="fa fa-comments"></span> Recomendaciones</button>
  <button class="tablinks" onclick="openCity(event, 'Tokyo')"> <span class="fa fa-file"></span> Políticas</button>
</div>

<div id="London" class="tabcontent">

  <h3>¿Cuál es el plan?</h3>
  <p><%= simple_format @experience.que_plan %></p>

  <h3>¿Qué incluye?</h3>
  <p><%= simple_format @experience.incluye %></p>

  <h3>Itinerario</h3>
  <p><%= simple_format @experience.itinerario %></p>


  <h3>Ubicación:</h3>
  <div id="map2"></div>

</div>

<div id="Paris" class="tabcontent">
  <h3>Recomendaciones:</h3>
  <p><%= simple_format @experience.recomendaciones %></p> 
</div>

<div id="Tokyo" class="tabcontent">
  <h3>Políticas: </h3>
<p><%= @experience.try(:politics) %></p> 
</div>

<br>
<br>
<h1 class="titulo">Dudas, comentarios o preguntas: </h1> <br>
        <a href="mailto:experiencias@intertravex.com?Subject=Solicitud%20de%20información"><h4 class="">experiencias@intertravex.com</h4></a><br>
        <a href="5528037574"><h4>Teléfono: (+52) 55 2803 7574</h4></a> <br>

<!-- tabs -->
</div>


<script>
function openCity(evt, cityName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(cityName).style.display = "block";
    evt.currentTarget.className += " active";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>

<script>

  function initMap() {
    var myLatLng = {lat: <%= @experience.latitude %>, lng: <%= @experience.longitude %>};

    var map = new google.maps.Map(document.getElementById('map2'), {
      zoom: 12,
      center: myLatLng,
      scrollwheel: false
    });


    var marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      title: '<%= @experience.nombre %>'
    });
  }

</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB6K3XNvvLlBjourkCDTo3CMOUygthuYKo&signed_in=true&callback=initMap"></script>

app/views/experiences/edit.html.erb
<%= render 'welcome/bread' %>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    	<h2 class="center">Editar Experiencia <%=@experience.nombre %></h2>

<%= render 'form', experience: @experience %>

<%= link_to 'Ver Experiencia', @experience %> |
<%= link_to 'Atrás', experiences_path %>

</div>
</div>
</div>

app/views/experiences/index.html.erb
<div class="container">
  <div id="titulos">
    <h1 class="titulo center">Justo las experiencias que estás buscando</h1>
    <p class="center">Conoce las diferentes opciones para conocer en esta temporada</p>
  </div>
</div>

<div class="container">
<div id="search">
  <%= search_form_for @q do |f| %>
  <ul>
    <li>
      <%= f.search_field :nombre_cont, placeholder: "Buscar por Lugar...", id: "icon", sytle: "text-indent:30px;"  %>
    </li>
    <li>
      <%= f.search_field :categoria_cont, placeholder: "Tipo de Experiencia...", id: "icon2", sytle: "text-indent:30px;"  %>
    </li>
    <li>
      <%= f.search_field :categoria_cont, id: "icon3", sytle: "text-indent:30px;", placeholder: " Número de días..."  %>
    </li>
    <li>
      
      <%= f.submit "Buscar", class: "button2 button_blue" %>
    </li>
  </ul>
  <% end %>
</div>
</div>


<div class="container">
<div id="expes">
  <div class="row">

    <% @experiences.each do |experience| %>
<div class="col-md-4 col-sm-6">
      <div id="expes_1">
      <div class="imagen">
        <%= image_tag experience.foto.thumb %>
      </div>
      <div class="datos">
        <h5><%= experience.categoria %></h5>
        <h3><%= experience.nombre %></h3>
        <h6> <span class="fa fa-map-marker"> </span> <%= experience.lugar %></h6>
        <%= link_to experience do %>
        <button class="button button_blue2">Conoce más! -></button>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>

</div>

</div>
</div>



<br>

app/views/experiences/new.html.erb
<%= render 'welcome/bread' %>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

<h2 class="center">Nueva Experiencia</h2>

<%= render 'form', experience: @experience %>

<%= link_to 'Atrás', experiences_path %>


</div>
</div>
</div>

app/views/experiences/show.html.erb
<div class="hero4" style="background: linear-gradient(to right, rgba(75, 123, 211, 0.5), rgba(22, 215, 177, 0.3)),    url(<%=@experience.foto.heavy %>);">

  <h1 class="white center"><%= @experience.nombre %></h1>
</div>

<div class="container">
  
<div id="show_ex">
  <div class="row">
    <div class="col-md-7">
      <div id="ex_iz">
        <h1><%= @experience.nombre %></h1>
        <h3> <span class="fa fa-map-marker"> </span> <%= @experience.lugar %></h3>
        <h3> <span class="fa fa-map-marker"> </span> <%= @experience.categoria %></h3>

        <p><%= simple_format @experience.descripcion %></p>

        <h4><%= @experience.dias %></h4>
        <p>
        <% @blocks.each_with_index do |block, i| %>
          <%= block.fecha_salida.strftime(" %b-%d-%Y") %>,
        <% end %>
        </p>
      </div>
    </div>

    <div class="col-md-5">
      <div id="ex_der">
        <div class="owl-carousel">
            <% @images.each do |image| %>
            <div><%= image_tag image.image2.max.url %></div>
            <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

<%= render 'share' %>

<div id="show_ex">
  <div class="row">
  <div class="col-md-7">
<%= render 'tabs' %>
  </div>
  <div class="col-md-5">
    <div id="paquetes">
      <h2 class="center">Fechas Disponibles</h2>
      <h2 class="center"><%= @experience.nombre %></h2>
      <hr>

<div id="bloques">
      <% @blocks.each_with_index do |block, i| %>
      <div id="contact2"> <br>
        <h4> Lugar de salida: <%= block.lugar_salida %></h4>
        <h4> Hora de salida: <%= block.hora_salida.strftime("%H:%M") %></h4>
        <h4>Fechas: <%=block.fecha_salida.strftime(" %b-%d-%Y")%> - <%= block.fecha_regreso.strftime(" %b-%d-%Y") %></h4>
        
        <%  if block.experience.dias == "1 día" %>
        <h4>Precio de adulto: <%= number_to_currency block.precio_adulto%></h4>
        <h4>Precio de niño: <%= number_to_currency block.precio_nino%></h4>
        <h4>Disponibilidad: <%= block.capacidad %> personas</h4>
        <% else %>
        <h4>Habitación doble: <%= number_to_currency block.habitacion_doble%></h4>
        <h4>Habitación triple: <%= number_to_currency block.habitacion_triple%></h4>
        <h4>Habitación cuádruple: <%= number_to_currency block.habitacion_cuadruple %></h4>
        <h4>Menor extra: <%= number_to_currency block.menor_extra %></h4>
        <p>**Precios por persona en base a la ocupación seleccionada</p>
        <% end %>




        <%  if block.experience.dias == "1 día" %>
        <%= link_to new_block_order_path(block), data: { no_turbolink: true } do %>
            <button class="button button_blue button_block">Reservar</button>
        <% end %>

        <% else %>

        <%= link_to new_block_package_path(block), data: { no_turbolink: true } do %>
            <button class="button button_blue button_block">Reservar</button>
        <% end %>
        <% end %>

      </div>
    <% end %>
</div>
    </div>
  </div>
  </div>
</div>

<hr>

<div class="container">
  <div id="titulos">
    <h1 class="titulo center">¿Cómo reservo esta experiencia?</h1>
    <p class="center">Vivir una experiencia única con nosotros es lo más sencillo:</p>
  </div>
</div>

<div class="container">
  <div id="nume">
  <div class="row">
    <div class="col-md-2 col-xs-4 col-md-offset-3">
      <div id="nume_1">
        <%= image_tag "uno.png" %>
        
        <p class="center">Elige la fecha y hora que más te acomoda</p>
      </div>
    </div>

    <div class="col-md-2 col-xs-4">
      <div id="nume_1">
        <%= image_tag "dos.png" %>
        
        <p class="center">Selecciona el número de personas que van</p>
      </div>
    </div>

    <div class="col-md-2 col-xs-4">
      <div id="nume_1">
        <%= image_tag "tres.png" %>
        
        <p class="center">Recibe la confirmación del viaje</p>
      </div>
    </div>
  </div>
</div>
</div>



<div id="expes">
  <div class="row">
    <h1 class="titulo center">Otras Experiencias que te pueden interesar</h1>
    <p class="center">Porque una vez que empiezas a conocer las maravillas de México no te puedes detener</p> <br><br>

    <% @experiences.each do |experience| %>
<div class="col-md-4 col-sm-6">
      <div id="expes_1">
      <div class="imagen">
        <%= image_tag experience.foto.thumb %>
      </div>
      <div class="datos">
        <h5><%= experience.categoria %></h5>
        <h3><%= experience.nombre %></h3>
        <h6> <span class="fa fa-map-marker"> </span> <%= experience.lugar %></h6>
        <%= link_to experience do %>
        <button class="button button_blue2">Conoce más! -></button>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>


</div>
</div>

<!-- end container -->
</div>

<% if user_signed_in? && current_user.admin? %>
<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>
<% end %>


<script>
  $(".owl-carousel").owlCarousel(
  {
    items:1,
    autoHeight:true,
  });
</script>