config/routes.rb
Rails.application.routes.draw do

  
  resources :packages do
    resources :rooms
  end 
  get 'orders/new'

  resources :blocks do 
  	resources :orders
    resources :packages
  end
  
  resources :images
  resources :experiences
  get 'viajes_corporativos' => 'pages#corporativos'
  get 'mis_experiencias' => 'pages#mis_experiencias'

  resources :contacts, only: [:new, :create]
	mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  root 'welcome#index'

  resources :orders, only: [:index]
  resources :packages, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :experience
  has_many :orders, dependent: :destroy
  has_many :packages, dependent: :destroy
end

app/models/contact.rb
class Contact < MailForm::Base

	attribute :name, 					:validate => false
	attribute :email, 				:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :phone,     		:validate => false
	attribute :service, 			:validate => false
	attribute :donde, 		   	:validate => false
	attribute :comments, 			:validate => false
	attribute :nickname, 			:captcha => true

def headers 
	{
	:subject => "Nueva Confirmación",
	:to => "alex@idearialab.com",
	:cc => "alejandroromo14@gmail.com",
	:from => %("#{name}" <#{email}>)
	}
	end
end

app/models/experience.rb
class Experience < ApplicationRecord
	mount_uploader :foto, FotoUploader
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images

  has_many :blocks, dependent: :destroy
  accepts_nested_attributes_for :blocks, :reject_if => lambda { |a| a[:lugar_salida].blank? }, :allow_destroy => true
  extend FriendlyId
  friendly_id :nombre, use: :slugged

geocoded_by :lugar
after_validation :geocode, if: ->(obj){ obj.lugar.present? and obj.lugar_changed? }
after_validation :lat_changed?

private

# This is used to make sure that our lugar is actually parsed properly and we
# get a valuable lat/long
def lat_changed?
    if (self.lugar_changed?)
        if !(self.latitude_changed?)
            self.errors.add(:lugar, ": La ubicación no es válida")
            return false
        end
    end
    return true
end

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :experience
  mount_uploader :image2, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :block
  



end

app/models/package.rb
class Package < ApplicationRecord
  
  belongs_to :block
  has_many :rooms, dependent: :destroy
end

app/models/room.rb
class Room < ApplicationRecord
  
  belongs_to :package

validate :habitacion_doble
validate :habitacion_triple
validate :habitacion_cuadruple

def habitacion_doble
	if self.tipo_habitacion == "Habitación Doble" && self.num_adultos >= 3
	errors.add(:room_id, "No se pueden más de dos adultos en habitación doble") 
  end 
end


def habitacion_triple
	if self.tipo_habitacion == "Habitación Triple" && self.num_adultos >= 4
	errors.add(:room_id, "No se pueden más de dos adultos en habitación doble") 
  end 
end


def habitacion_cuadruple
	if self.tipo_habitacion == "Habitación Cuádruple" && self.num_adultos >= 5
	errors.add(:room_id, "No se pueden más de dos adultos en habitación doble") 
  end 
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :experiences

  validates :name, presence: true

  # after_create :create_a_customer

  # def create_a_customer
		# Stripe.api_key = Rails.application.secrets.stripe_secret_key # set the secret key to identify with stripe.	
  	
  # 	customer = Stripe::Customer.create(
  # 		:card => token,
  # 		:email => self.email
  # 		)     
  # 	self.stripe_card_token = customer.id
  # 	save!
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= display_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <script defer src="https://use.fontawesome.com/releases/v5.1.1/js/all.js" integrity="sha384-BtvRZcyfv4r0x/phJt9Y9HhnN5ur1Z+kZbKVgzVBAlQZX4jvAuImlIz+bG7TS00a" crossorigin="anonymous"></script>


  <% if params[:controller] == "orders" and params[:action] == "new" or params[:action] == "create" %>

  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
        // This identifies your website in the createToken call below
        Stripe.setPublishableKey('<%= Rails.application.secrets.stripe_public_key %>');
        // ...
  </script>
  <% elsif params[:controller] == "packages" and params[:action] == "show" %>
  
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
        // This identifies your website in the createToken call below
        Stripe.setPublishableKey('<%= Rails.application.secrets.stripe_public_key %>');
        // ...
  </script>

      <% end %>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src=“https://www.googletagmanager.com/gtag/js?id=UA-118956825-1“></script>
<script>
 window.dataLayer = window.dataLayer || [];
 function gtag(){dataLayer.push(arguments);}
 gtag(‘js’, new Date());

 gtag(‘config’, ‘UA-118956825-1’);
</script>
    </head>

    <body>



      <% flash.each do |key, value| %>
      <div class="<%= key %>">
        <p><%= value %></p>
      </div>
      <% end %>

      <div id="navin">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to root_path do %>
              <%= image_tag "logo2.png" %>
              <% end %>
            </div>


            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li class="<%= 'activo' if current_page?(experiences_path) %>"><a href="<%=experiences_path %>">Experiencias</a></li>
                <li class="<%= 'activo' if current_page?(viajes_corporativos_path) %>"><a href="<%=viajes_corporativos_path %>">Servicios Corporativos</a></li>
                <li class="<%= 'activo' if current_page?(new_contact_path) %>"><a href="<%=new_contact_path %>">Contacto</a></li>
                <% if user_signed_in? && current_user.admin? %>
                <li>
                  <%= link_to 'Dashboard', mis_experiencias_path %>
                </li>
                <% end %>
                <% if user_signed_in? %>
                <li class="mini"> <a href="<%= destroy_user_session_path %>" data-method='delete'>
                  Cerrar Sesión
                </a></li>
                <% else %>
                <li class="mini"><a href="<%= new_user_session_path %>"> Iniciar Sesión </a></li>
                <li class="mini"><a href="<%= new_user_registration_path %>"> Regístrate </a></li>
                <% end %>

              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
      </div>


      <div id="content">
        <%= yield %>
      </div>


      <div id="footer">
       <div class="row">
        <div class="col-sm-2">
         <div id="sube">
           <%= image_tag "logo3.png" %> <br><br><br><br>
         </div>
       </div>


       <div class="col-md-8 col-xs-6">
        <h5 class="white">Inter Travex</h5>

        <%= link_to experiences_path do %>
        <p>Experiencias</p>
        <% end %>

        <%= link_to viajes_corporativos_path do %>
        <p>Corporativos</p>
        <% end %>

        <%= link_to new_contact_path do %>
        <p>Contacto</p>
        <% end %>
        <br>
        <a href="mailto:experiencias@intertravex.com?Subject=Solicitud%20de%20información"><p>experiencias@intertravex.com</p></a>
        
        <a href="5528037574"><p><%=image_tag "whats.png" %></span> (+52) 55 2803 7574</p></a> <br>
      </div>

      <div class="col-sm-2 col-xs-6">
        <div id="sube">
          <ul>
            <li>
              <%= link_to "https://www.facebook.com/intertravex/" do %>
              <%= image_tag "facebook.png" %>
              <% end %>
            </li>

<!--             <li>
              <%#= link_to root_path do %>
              <%#= image_tag "insta.png" %>
              <%# end %>
            </li>

            <li>
              <%#= link_to root_path do %>
              <%#= image_tag "twitter.png" %>
              <%# end %>
            </li> -->
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="cuadrito">
   <h2>Copyright © 2018. All Rights Reserved.</h2>
 </div>



 <script>
  jQuery(function($) {
  $('#new_order').submit(function(event) { // change $('#payment-form') to $('#new_order')
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});


  function stripeResponseHandler(status, response) {
  var $form = $('#new_order'); // change the selector that gets the form to #new_order

  if (response.error) {
    // Show the errors on the form
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // response contains id and card, which contains additional card details
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="order[stripe_token]" />').val(token)); // Change the name attribute to correspond to rails' expected format for the params object.
    // and submit
    $form.get(0).submit();
  }
}
</script>

</body>
</html>

app/views/pages/corporativos.html.erb
<div class="hero3">
	<h1 class="white center">Servicios Corporativos</h1>
	<div class="col-md-6 col-md-offset-3">
	<p class="white center hidden-xs"> </p>
	</div>
</div>

<div id="bluish">
	<br><br>	
	<div class="container">
		<div id="contact">
			<div class="row">
				<div class="col-md-6 visible-sm visible-xs">
					<div id="contact_izq">
						<%= image_tag "banner_home3.jpg"%>
					</div>
				</div>
				<div class="col-md-6">
					<div id="contact_der">
						<p class="white">Nuestro principal objetivo es adaptarnos a las necesidades del cliente ofreciendo un servicio de administración integral en la organización de eventos empresariales; desde eventos de integración, congresos, convenciones, viajes de incentivos, team building, seminarios, conferencias de trabajo, capacitaciones, cenas empresariales o cualquier tipo de espectáculo. <br> Nos satisface ofrecer a nuestros clientes un servicio completo de logística de transportación y garantizar el éxito en sus eventos.</p>
					</div>
				</div>
				<div class="col-md-6 hidden-sm hidden-xs">
					<div id="contact_izq">
						<%= image_tag "banner_home3.jpg"%>
					</div>
				</div>

			</div>
		</div>
	</div>

	<div class="container">
		<div id="fotos_cont">
			<div class="owl-carousel">
				<div><%= image_tag "banner_home4.jpg" %></div>
				<div><%= image_tag "banner_home5.jpg" %></div>
				<div><%= image_tag "banner_home6.jpg" %></div>
				<div><%= image_tag "banner_home7.jpg" %></div>
			</div>
		</div>
	</div>

	<div class="container">
		<div id="titulos">
			<h1 class="titulo center white">Beneficios</h1>
			<p class="center white">Intertravex puede ser un elemento clave para la organización de tus eventos.</p>
		</div>
	</div>



<div id="yeaks">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<div id="producto">
					<%= image_tag "planear.png" %>
					<h2 class="white">Planeamos</h2>
				</div>
			</div>

			<div class="col-md-4">
				<div id="producto">
					<%= image_tag "corporativos.png" %>
					<h2 class="white">Desarrollamos</h2>
				</div>
			</div>

			<div class="col-md-4">
				<div id="producto">
					<%= image_tag "experiencias.png" %>
					<h2 class="white">Ejecutamos</h2>
				</div>
			</div>
		</div>
	</div>
</div> <br><br>


<div class="container">
	<div id="nume">
	<div class="row">

		<div class="col-md-2 col-xs-4">
			<div id="nume_1">
				<%= image_tag "icono_04.png" %>
				<p class="white center">Hospedaje</p>
			</div>
		</div>

		<div class="col-md-2 col-xs-4">
			<div id="nume_1">
				<%= image_tag "icono_05.png" %>
				<p class="white center">Congresos</p>
			</div>
		</div>

		<div class="col-md-2 col-xs-4">
			<div id="nume_1">
				<%= image_tag "icono_06.png" %>
				<p class="white center">Salones de Eventos</p>
			</div>
		</div>

		<div class="col-md-2 col-xs-4">
			<div id="nume_1">
				<%= image_tag "icono_02.png" %>
				<p class="white center">Transportación</p>
			</div>
		</div>

		<div class="col-md-2 col-xs-4">
			<div id="nume_1">
				<%= image_tag "icono_03.png" %>
				<p class="white center">Eventos Especiales</p>
			</div>
		</div>

		<div class="col-md-2 col-xs-4">
			<div id="nume_1">
				<%= image_tag "icono_01.png" %>
				<p class="white center">Cenas empresariales</p>
			</div>
		</div>

	</div><br><br>
				<h1 class="titulo center white">Cuéntanos tu próxima experiencias con nosotros</h1> <br>
        <a href="mailto:ventas@intertravex.com?Subject=Solicitud%20de%20información"><h4 class="white">ventas@intertravex.com</h4></a>
</div>
</div>


<div id="mancha2"></div>

<div class="container">
		<div class="col-md-8 col-md-offset-2" style="padding: 0px;">
			<div id="contact2" class="up">
				<h2>Contáctanos</h2>

			<%= form_for @contact do |f| %>
			<div class="field">
				<%= f.label :Nombre %><br>
				<%= f.text_field :name, required:true %>
			</div>

			<div class="field">
				<%= f.label :Email %><br>
				<%= f.email_field :email, required:true %>
			</div>

			<div class="field">
				<%= f.label :Teléfono %><br>
				<%= f.email_field :phone %>
			</div>

			<%= f.text_field :donde, :value => "#{params[:controller]} - #{request.original_url}", class: "hidden" %>

			<div class="field">
				<%= f.label :Mensaje %><br>
				<%= f.text_area :comments, required:true %>
			</div>

			<div class="hidden">
				<%= f.label :nickname %><br>
				<%= f.text_field :nickname, hint: 'Esto se queda en blanco' %>
			</div>

			<div class="but">
				<%= f.submit "Enviar", class:"button button_blue button_center"%>
			</div>
			<% end %>

			</div>
	</div>
</div>





</div>



<script>
	$(".owl-carousel").owlCarousel(
	{
		items:4,
		autoHeight:true,
	});
</script>

app/views/pages/mis_experiencias.html.erb
<%= render 'welcome/bread' %>

<div id="tablon">
<div class="container">
<div class="content table-responsive table-full-width">
      <table class="table table-hover table-striped">
        <thead>
          <th>ID</th>
          <th>Status</th>
          <th>Nombre</th>
          <th>Categoría</th>
          <th># Paquetes</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @experiences.each do |experience| %>
          <tr>
            <td><%= experience.id%></td>
            <td><%= experience.disponible %></td>
            <td><%= experience.nombre %></td>
            <td><%= experience.categoria %></td>
            <td><%= experience.blocks.count %></td>
            <td><%= link_to 'Ver más', experience %></td>
            <td><%= link_to 'Editar', edit_experience_path(experience) %></td>
            <td><%= link_to 'Eliminar', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
   </div>
</div>